---
timezone: Europe/London
nameserver: 1.1.1.1

nfs_mounts:
  - path: /mnt/bot-data
    src: "{{ nfs_server }}:/mnt/tank/bot-data"
    opts: defaults,_netdev,nofail
  - path: /mnt/cc-shared
    src: "{{ nfs_server }}:/mnt/tank/cc-shared"
    opts: defaults,_netdev,nofail

base_packages:
  - curl
  - wget
  - git
  - vim
  - htop
  - nfs-common
  - ca-certificates
  - gnupg
  - lsb-release
  - python3
  - python3-pip
