apiVersion: v1
kind: Service
metadata:
  name: atlas-nutrition-tracker-service
spec:
  type: NodePort
  selector:
    app: atlas-nutrition-tracker
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30505
